version: '3.8'

services:
  nodered:
    image: nodered/node-red:latest
    container_name: nodered
    restart: unless-stopped
    ports:
      - "1880:1880"
    volumes:
      - ./data:/data
    environment:
      - TZ=America/Sao_Paulo
      - NODE_RED_ADMIN_ROOT=/nodered
      - NODE_RED_NODE_ROOT=/nodered
      - NODE_RED_WEBSOCKET_PATH=/nodered/comms
